@startuml
'https://plantuml.com/class-diagram
enum Hazard{
    BLOCKAGE
}

enum Difficulty{
    EASY
    NORMAL
    HARD
    EXPERT
}

class Report{
    +hazardType: Hazard
    +message: String
    +location: Location
    +constructor(hazard: Hazard, location: Location, message: String)
    +postReport(): Boolean CHECK THIS LATER!!!!!!!!!!!!!!!

}
class Mountain{
    -mountainId: Int
    -location: Location
    -description: String
    -weather: Weather ; DARI API HARUSNYA
    -route: List<Route>
}
class User {
    +userId : Int
    +name: String
    +username: String
    +email: String
    +password: String
    +profilePictureUrl: String
    +bio: String
    +dateOfBirth: Date
    +location: Location
    +followersCount: Int
    +followingCount: Int
    +postsCount: Int
    +lastActive: Date
    +post: List<Post>
    +post(): Boolean
    +confirmTrack(): Boolean

}

class Comment{
    -userId: Int
    -message: String
}
class Like{
    -userId: Int
}
class Location {
    +latitude: Double
    +longitude: Double
    +altitude: Double
}

abstract class Post {
    +postId: Int
    +title: String
    +dateCreated: Date
    +author: String
    +comments: List<Comment>
    +likes: List<Like>
    +location: Location
    +description: String
    +route: Route
    -duration: Int


    +constructor(postId: Int, title: String, author: String, location: Location, description: String)

    +comment(comment: Comment): Boolean
    +deleteComment(comment: Comment): Boolean

    +like(like: Like): Boolean
    +unlike(like: Like): Boolean

    +delete(): Boolean
    +report(message: String): Boolean



}

class Route{
    -path: List<Location>
    -difficultyType: Difficulty
    -totalDistance: Double
    -distanceUp: Double
    -distanceDown: Double


}

class VideoPost {
    +videoUrl: String
    +duration: Int
}

class ImagePost {
    +imageUrl: String
    +resolution: String
}
User o-- Location
Post o-- Route
Post o-- Comment
Post o-- Like
Post o-- Location
Report *-- Hazard
Post <|-- VideoPost
Post <|-- ImagePost
Route *-- Difficulty
User o-- Post
Mountain o-- Location
Report o-- Location
@enduml